name: spring
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  google_fonts: ^4.0.4
  firebase_auth: ^4.17.2
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.15.2
  requests: ^4.7.0
  firebase_storage: ^11.6.3
  logger: ^2.0.2
  intl: ^0.18.1
  http: ^0.13.4
  get: ^4.6.6
  shared_preferences: ^2.2.2
  adaptive_theme: ^3.6.0
  dictionaryx: ^0.3.5
  expandable_text: ^2.3.0
  gif_view: ^0.3.1
  pedometer: ^4.0.1
  circular_countdown_timer: ^0.2.3
  audioplayers: ^5.2.1
  fl_chart: ^0.36.2
  flutter_local_notifications: ^9.1.5
  flutter_gemini: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/pets/cat/
    - assets/audio/
