// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZVb13K7gF5O4EtRhoCdSr4E9mmiPiMJI',
    appId: '1:610922772594:android:7e41566e1637574bf82aeb',
    messagingSenderId: '610922772594',
    projectId: 'spring-a-ling',
    databaseURL: 'https://spring-a-ling-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spring-a-ling.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUiwvURbh7mK3yZO2nCSCDdi3SfwFpUtc',
    appId: '1:610922772594:ios:55c3cdf512de7798f82aeb',
    messagingSenderId: '610922772594',
    projectId: 'spring-a-ling',
    databaseURL: 'https://spring-a-ling-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spring-a-ling.appspot.com',
    iosClientId: '610922772594-jhmupckdcogdaphq3653tgn6c4ar5krk.apps.googleusercontent.com',
    iosBundleId: 'com.example.spring',
  );
}
